name: Connor McSheffrey - Designer and Developer
description: Connor McSheffrey is a UI designer living in SoMA San Francisco who appreciates good coffee bicycles and poloroids.
url: http://www.connormcsheffrey.com
permalink: /:title
redirects: yes
pygments: true